version: '3.8'
services:  
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8888:8000'
    volumes:
      - ./data:/data
  # command:
  #   - start #start the SurrealDB server
  #   - --log=trace #no idea what this does :(
  #   - --user=root #default user
  #   - --pass=root #default password
    entrypoint:
      - /surreal 
      - start
      - file:/data/archiver.db
    restart: always
  

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=127.0.0.1

